 name: Rustic
 version: 1
 description: Rustic MC's Core Plugin
 author: RustyDesigns
 softdepend: []
 
 main: me.rusty.rustycore.Core
 
 commands:
   help:
     description: Displays the help message!
     usage: Oops, please check your permissions and try again.
   spawn:
     description: Teleports you to spawn!
     usage: Oops, please check your permissions and try again.
   gm:
     description: Gamemode!
     usage: Oops, please check your permissions and try again.
   weather:
     description: Weather!
     usage: Oops, please check your permissions and try again.
   time:
     description: Time!
     usage: Oops, please check your permissions and try again.
   ci:
     description: Clear!
     usage: Oops, please check your permissions and try again.
   tp:
     description: TP!
     usage: Oops, please check your permissions and try again.
   kit:
     description: Kit!
     usage: Oops, please check your permissions and try again.
   sethome:
     description: SetHome!
     usage: Oops, please check your permissions and try again.
   home:
     description: Home!
     usage: Oops, please check your permissions and try again.
   hub:
     description: Teleport you to hub!
     usage: Oops, please check your permissions and try again.
   flyspeed:
     description: Sets your flying speed!
     usage: Oops, please check your permissions and try again.
   hd:
     description: Blocks Usage!
     usage: Oops, please check your permissions and try again.


